from .eduroam_web_scraper import generate_and_save_eduroam_for_user
from .eduroam_web_scraper import get_single_student_user_from_web_to_json
from .general_web import init_chrome_webdriver
from .general_web import init_firefox_webdriver
