from .eduroam_web_scraper import generate_eduroam_for_user
from .eduroam_web_scraper import get_single_student_user_from_web_to_json

from .general_web import init_chrome_webdriver
from .general_web import init_firefox_webdriver

from .student_web_scraper import import_student_from_web
